name: Deploy To Dev Server

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Create temporary .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Copy .env file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: ".env"
          target: "/home/ubuntu/toky"


      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            cd /home/ubuntu/toky
            git fetch origin
            git reset --hard origin/main
            
            yarn install
            yarn build

            pm2 restart toky || pm2 start dist/main.js --name toky
